### ISSUE TITLE
Issue with travis build

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/yggdrasil#13]
There seems to be some problem getting the build to work on travis that I think is related to one of the files having the wrong case. In particular, during the build it is looking for `Optics.cmxa` which does not exist, although `optics.cmxa` does. It may be the case that `ocamlbuild` or `rebuild` is causing this issue but it doesn't cause an error on my machine since OS X is case insensitive.

**Comment by freebroccolo** [comment]
Resolved.

**Comment by jonsterling** [comment]
so frustrating! This has happened to me a number of times, and I can never remember how I ended up fixing it.

**Comment by freebroccolo** [comment]
Yeah… it's horrible. The worst part is that I spent all that time thinking I set up the build on Linux incorrectly somehow when really it just should never have worked on OS X in the first place with a reasonable file system. I'll be so glad when they get rid of HFS.
