### ISSUE TITLE
trouble building

### ISSUE THREAD

**Issue by jonsterling** [freebroccolo/yggdrasil#13]
When I ran `opam pin add yggdrasil git://github.com/freebroccolo/yggdrasil.git`, I got the following:

```
Package yggdrasil does not exist, create as a NEW package ? [Y/n] y
yggdrasil is now git-pinned to git://github.com/freebroccolo/yggdrasil.git

[yggdrasil] Fetching git://github.com/freebroccolo/yggdrasil.git
Installing new package description for yggdrasil from git://github.com/freebroccolo/yggdrasil.git/opam

yggdrasil needs to be installed.
The following dependencies couldn't be met:
  - yggdrasil -> prelude
Your request can't be satisfied:
  - No package named prelude found.

No solution found, exiting
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

Then, I wasn't sure if this meant that it had totally failed, so I tried running `./script/build`, and I got the following:

```
./script/build: line 11: @: unbound variable
```

**Comment by freebroccolo** [comment]
Oh, sorry about that. You will need to have `prelude` pinned also. I'll update the README. The script thing is kind of wierd. What is the output you get from `bash -v`? I'm not actually using any arguments at the moment so you could just change the last line to `main` and it should work. I'll investigate.

**Comment by freebroccolo** [comment]
You should be able to rerun the build steps and I think it will work now. If it asks about repinning something, just say yes. With the most recent changes, you probably want to run `script/interface` now too.

**Comment by jonsterling** [comment]
Thank you! I'll try it again shortly

**Comment by freebroccolo** [comment]
I think there's another issue with building the interface in a fresh environment with the way I've described in the README. Doing some testing now…

**Comment by freebroccolo** [comment]
I think I fixed the other issues and updated the README again.

**Comment by freebroccolo** [comment]
So I noticed a few more issues earlier but I think I fixed those too after testing in a fresh switch. Think I probably need to setup travis or something…

**Comment by jonsterling** [comment]
Hmm, I just tried again and now I get 

```
~/s/o/yggdrasil ⊢ opam pin add yggdrasil git://github.com/freebroccolo/yggdrasil.git
[NOTE] Package yggdrasil is already pinned to git://github.com/freebroccolo/yggdrasil.git. This will reset metadata.
Proceed ? [Y/n]

[yggdrasil] Fetching git://github.com/freebroccolo/yggdrasil.git
Installing new package description for yggdrasil from git://github.com/freebroccolo/yggdrasil.git/opam

yggdrasil needs to be installed.
The following dependencies couldn't be met:
  - yggdrasil -> irmin-unix
Your request can't be satisfied:
  - No package named irmin-unix found.
```

**Comment by jonsterling** [comment]
Ah, I just ran `opam upgrade`, and this step seems to work now.

**Comment by jonsterling** [comment]
OK, here's what I get now:

```
yggdrasil needs to be installed.
The following actions will be performed:
 - install   nocrypto.0.5.1                        [required by websocket]
 - install   websocket.2.1                         [required by yggdrasil]
 - install   git.1.5.2                             [required by irmin-unix, irmin]
 - install   irmin.0.9.7                           [required by yggdrasil]
 - install   irmin-unix.0.9.4                      [required by yggdrasil]
 - install   yggdrasil.0.0.0*
=== + 6 ===
Do you want to continue ? [Y/n] y

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[yggdrasil] Fetching git://github.com/freebroccolo/yggdrasil.git

=-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] nocrypto-inhibit-modernity is not a valid variable.
[WARNING] Invalid variable nocrypto-inhibit-modernity in filter
[ERROR] 'nocrypto-inhibit-modernity' has type string, but a env element of type bool was expected.
[ERROR] The compilation of nocrypto.0.5.1 failed.
Removing nocrypto.0.5.1.
  ocamlfind remove nocrypto


#=== ERROR while installing nocrypto.0.5.1 ====================================#
Internal error:
  OpamFilter.Filter_type_error

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following failed
 - install   nocrypto.0.5.1
Due to the errors, the following have been cancelled
 - install   git.1.5.2
 - install   irmin.0.9.7
 - install   websocket.2.1
 - install   yggdrasil.0.0.0
 - install   irmin-unix.0.9.4
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by freebroccolo** [comment]
Ah, yeah, probably always want to make sure to do `opam update && opam upgrade` first. I'll add a note to the README.

Looks like nocrypto is failing to build. There have been a number of updates to major packages lately and I haven't been too careful about keeping on top of that. Maybe I should add bounds or something. I'll try it in a fresh switch real quick though.

**Comment by freebroccolo** [comment]
So I think the problem with nocrypto is what's described in the [README FAQ](https://github.com/mirleft/ocaml-nocrypto). See the big about "illegal instructions". I guess it has to do with nocrypto and hardware acceleration.

According to their instructions you can work around it by explicitly disabling that functionality when building it: 

```
switch=$(opam config var switch)
echo 'nocrypto-inhibit-modernity: true' >> ~/.opam/${switch}/config/global-config.config
```

However it also sounds like this might be fixed automatically in current `opam` versions. Not sure which version you have but you could try doing a `brew upgrade opam`. I think you can also use `opam` to install newer versions of itself.

Let me know if that works and thanks for reporting these issues :)

**Comment by jonsterling** [comment]
OK, I managed to build it now! Thanks for your help :)

**Comment by freebroccolo** [comment]
Great :)  Let me know if there are any other problems. I'll have to add a note about the nocrypto thing. Did you fix it with config variable or was it something else?
